### ISSUE TITLE
getting 0 logs

### ISSUE THREAD

**Issue by c-u-l8er** [mcampa/phoenix-client#4]
is this project still active? phoenix-channels doesn't seam to be working for me. here is a link to what I was trying to do (from line #11 and onward):

https://github.com/trabur/RAceFasT/blob/master/index.ts#L11

**Comment by mcampa** [comment]
I'm sorry but this is a fork I created for a personal project a few years ago to be able to use it with nodejs.
It is not maintained and I don't think is compatible with the current version of Phoenix.
